# Generated by Django 3.2 on 2023-03-30 12:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2023, 3, 30, 12, 41, 31, 460762, tzinfo=utc), verbose_name='Date published')),
                ('is_draft', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
    ]
