# Generated by Django 3.2 on 2023-03-30 12:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 30, 12, 56, 24, 655553, tzinfo=utc), verbose_name='Date published'),
        ),
    ]
